In [1]:
# import geopandas as gpd
# import geopy
# from shapely.geometry import Point
# from geopy.geocoders import Nominatim

import pandas as pd
import numpy as np
import mpu

pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 10000)
pd.set_option('display.width', 10000)


In [2]:
df = pd.read_excel('atm_bank_misr.xlsx')
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4263 entries, 0 to 4262
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   4263 non-null   int64  
 1   ID           4263 non-null   int64  
 2   governerate  4263 non-null   object 
 3   region       4263 non-null   object 
 4   Address      4263 non-null   object 
 5   Lat          4263 non-null   float64
 6   Long         4263 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 233.3+ KB


In [6]:
df.head()

Unnamed: 0  ID governerate            region                                        Address        Lat       Long
0           0   0   Al Fayyum  Markaz Al-Fayyum                  Alfayoum Beghous Alhoriea St.  29.304412  30.853546
1           1   1   Al Fayyum  Markaz Al-Fayyum                              Fayoum University  29.319696  30.835641
2           2   2   Al Fayyum  Markaz Al-Fayyum                            Fayoum AlHoriea St.  29.308199  30.842229
3           3   3   Al Fayyum   Markaz Sinnuris                               Sanoras - Fayoum  29.408575  30.865073
4           4   4   Al Fayyum       Markaz Itsa  194 Abo Bakr AlSiddiq St.- Atsa City - Fayoum  29.236966  30.790194

In [ ]:
df.iloc

In [3]:
lat_longs = np.array(df[['Lat','Long']])#

In [8]:
k = 2

for i in range(len(lat_longs)):
    
    err_list = []
    
    for j in range(len(lat_longs)): 
        
        lat1,lon1,lat2,lon2 = lat_longs[i][0],lat_longs[i][1],lat_longs[j][0],lat_longs[j][1]
        
        err_list.append(mpu.haversine_distance((lat1, lon1), (lat2, lon2)))
    
    least_k = np.argsort(np.array(err_list))[1:k]
    
    print('Indexes of nearest lat_long',least_k)
    
    print('For lat_long',lat_longs[i],'the nearest lat_longs are:')
    print(lat_longs[least_k])
    
    print('With distances of:')
    print(np.array(err_list)[least_k])
    print('-------------------------------------')
    
    
    
    
    

Indexes of nearest lat_long [21]
For lat_long [29.30441208 30.85354563] the nearest lat_longs are:
[[29.3029927  30.85296321]]
With distances of:
[0.1676278]
-------------------------------------
Indexes of nearest lat_long [32]
For lat_long [29.319696 30.835641] the nearest lat_longs are:
[[29.319696 30.835641]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2]
For lat_long [29.308199 30.842229] the nearest lat_longs are:
[[29.308199 30.842229]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [16]
For lat_long [29.40857519 30.86507307] the nearest lat_longs are:
[[29.4087034 30.8587204]]
With distances of:
[0.61552473]
-------------------------------------
Indexes of nearest lat_long [28]
For lat_long [29.23696578 30.79019445] the nearest lat_longs are:
[[29.237697 30.795299]]
With distances of:
[0.50191914]
-------------------------------------
Indexes of nearest lat_long [29]
For lat_long [29.30772

Indexes of nearest lat_long [153]
For lat_long [30.912765 30.295561] the nearest lat_longs are:
[[30.912765 30.295561]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [47]
For lat_long [31.026177 30.451221] the nearest lat_longs are:
[[31.026177 30.451221]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [48]
For lat_long [30.912211 30.170589] the nearest lat_longs are:
[[30.912211 30.170589]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [49]
For lat_long [30.829702 30.535141] the nearest lat_longs are:
[[30.829702 30.535141]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [187]
For lat_long [31.099697 30.311892] the nearest lat_longs are:
[[31.099697 30.311892]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [163]
For lat_long [30.57747  30.710336] the nearest lat_longs ar

Indexes of nearest lat_long [133]
For lat_long [31.184945 30.52952 ] the nearest lat_longs are:
[[31.184945 30.52952 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [134]
For lat_long [31.175947 30.529477] the nearest lat_longs are:
[[31.175947 30.529477]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [92]
For lat_long [30.699037 30.668604] the nearest lat_longs are:
[[30.699037 30.668604]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [138]
For lat_long [30.886553 30.667319] the nearest lat_longs are:
[[30.88655  30.667319]]
With distances of:
[0.00033358]
-------------------------------------
Indexes of nearest lat_long [149]
For lat_long [31.036522 30.456495] the nearest lat_longs are:
[[31.036522 30.456495]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [95]
For lat_long [31.04408  30.475274] the nearest lat

Indexes of nearest lat_long [109]
For lat_long [31.040307 30.468207] the nearest lat_longs are:
[[31.040307 30.468207]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [65]
For lat_long [31.03936  30.455253] the nearest lat_longs are:
[[31.03936  30.455253]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [93]
For lat_long [30.88655  30.667319] the nearest lat_longs are:
[[30.886553 30.667319]]
With distances of:
[0.00033358]
-------------------------------------
Indexes of nearest lat_long [139]
For lat_long [31.03975  30.458095] the nearest lat_longs are:
[[31.03975  30.458095]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [76]
For lat_long [31.04241948 30.46890924] the nearest lat_longs are:
[[31.04241948 30.46890924]]
With distances of:
[5.25693289e-07]
-------------------------------------
Indexes of nearest lat_long [195]
For lat_long [30.86942495 30.70

Indexes of nearest lat_long [73]
For lat_long [30.91144225 30.17490715] the nearest lat_longs are:
[[30.91078908 30.17701905]]
With distances of:
[0.21416911]
-------------------------------------
Indexes of nearest lat_long [49]
For lat_long [30.82955574 30.53589971] the nearest lat_longs are:
[[30.829702 30.535141]]
With distances of:
[0.07424665]
-------------------------------------
Indexes of nearest lat_long [93]
For lat_long [30.88808594 30.67314422] the nearest lat_longs are:
[[30.886553 30.667319]]
With distances of:
[0.58141969]
-------------------------------------
Indexes of nearest lat_long [77]
For lat_long [30.92230447 29.95121672] the nearest lat_longs are:
[[30.81405902 29.98830245]]
With distances of:
[12.54601409]
-------------------------------------
Indexes of nearest lat_long [68]
For lat_long [31.02893672 30.71354872] the nearest lat_longs are:
[[31.03052168 30.71357679]]
With distances of:
[0.17625937]
-------------------------------------
Indexes of nearest lat

Indexes of nearest lat_long [276]
For lat_long [30.79787371 31.00133273] the nearest lat_longs are:
[[30.7968462 31.0020283]]
With distances of:
[0.13216601]
-------------------------------------
Indexes of nearest lat_long [251]
For lat_long [30.97070599 30.9569079 ] the nearest lat_longs are:
[[30.9669702  30.95712002]]
With distances of:
[0.41589373]
-------------------------------------
Indexes of nearest lat_long [321]
For lat_long [30.79225101 31.01074536] the nearest lat_longs are:
[[30.79397192 31.00686315]]
With distances of:
[0.41728644]
-------------------------------------
Indexes of nearest lat_long [301]
For lat_long [30.72743801 31.12104115] the nearest lat_longs are:
[[30.73088075 31.11671518]]
With distances of:
[0.56348742]
-------------------------------------
Indexes of nearest lat_long [304]
For lat_long [30.88240156 31.23455724] the nearest lat_longs are:
[[30.88240156 31.23455724]]
With distances of:
[3.07129858e-07]
-------------------------------------
Indexes 

Indexes of nearest lat_long [222]
For lat_long [30.939667 30.805887] the nearest lat_longs are:
[[30.93906548 30.81398976]]
With distances of:
[0.77567531]
-------------------------------------
Indexes of nearest lat_long [267]
For lat_long [30.961457 31.244514] the nearest lat_longs are:
[[30.96170513 31.24650627]]
With distances of:
[0.19195804]
-------------------------------------
Indexes of nearest lat_long [215]
For lat_long [31.09226754 31.14370783] the nearest lat_longs are:
[[31.09226754 31.14370783]]
With distances of:
[3.46908444e-07]
-------------------------------------
Indexes of nearest lat_long [266]
For lat_long [30.78503698 30.99363048] the nearest lat_longs are:
[[30.78503698 30.99363048]]
With distances of:
[3.47003723e-07]
-------------------------------------
Indexes of nearest lat_long [217]
For lat_long [30.88198283 30.96524633] the nearest lat_longs are:
[[30.88198283 30.96524633]]
With distances of:
[2.22389477e-07]
-------------------------------------
Indexe

Indexes of nearest lat_long [233]
For lat_long [30.78020191 31.01075553] the nearest lat_longs are:
[[30.78020191 31.01075553]]
With distances of:
[4.54910224e-07]
-------------------------------------
Indexes of nearest lat_long [423]
For lat_long [28.11789004 30.74257455] the nearest lat_longs are:
[[28.11789004 30.74257455]]
With distances of:
[3.14535448e-07]
-------------------------------------
Indexes of nearest lat_long [337]
For lat_long [28.08965662 30.76313344] the nearest lat_longs are:
[[28.09186301 30.76335211]]
With distances of:
[0.24627526]
-------------------------------------
Indexes of nearest lat_long [362]
For lat_long [28.42174871 30.79030213] the nearest lat_longs are:
[[28.42108579 30.79008335]]
With distances of:
[0.07675595]
-------------------------------------
Indexes of nearest lat_long [425]
For lat_long [28.09186301 30.76335211] the nearest lat_longs are:
[[28.09186301 30.76335211]]
With distances of:
[4.44847245e-07]
------------------------------------

Indexes of nearest lat_long [390]
For lat_long [28.41989818 30.78846619] the nearest lat_longs are:
[[28.42056544 30.78749442]]
With distances of:
[0.12056672]
-------------------------------------
Indexes of nearest lat_long [427]
For lat_long [28.09168308 30.7644408 ] the nearest lat_longs are:
[[28.09168308 30.7644408 ]]
With distances of:
[2.96545993e-07]
-------------------------------------
Indexes of nearest lat_long [387]
For lat_long [28.64973595 30.83933781] the nearest lat_longs are:
[[28.65020127 30.84215794]]
With distances of:
[0.28001244]
-------------------------------------
Indexes of nearest lat_long [338]
For lat_long [27.73652576 30.84757427] the nearest lat_longs are:
[[27.73721029 30.84510069]]
With distances of:
[0.25506685]
-------------------------------------
Indexes of nearest lat_long [421]
For lat_long [28.10225681 30.75295038] the nearest lat_longs are:
[[28.10225681 30.75295038]]
With distances of:
[2.22389872e-07]
-------------------------------------
In

Indexes of nearest lat_long [379]
For lat_long [28.09596611 30.76199947] the nearest lat_longs are:
[[28.09596611 30.76199947]]
With distances of:
[2.43062218e-07]
-------------------------------------
Indexes of nearest lat_long [381]
For lat_long [28.09168308 30.7644408 ] the nearest lat_longs are:
[[28.09168308 30.7644408 ]]
With distances of:
[2.96545993e-07]
-------------------------------------
Indexes of nearest lat_long [370]
For lat_long [28.12142828 30.74163879] the nearest lat_longs are:
[[28.12142828 30.74163879]]
With distances of:
[3.92273783e-07]
-------------------------------------
Indexes of nearest lat_long [357]
For lat_long [28.10914764 30.7516616 ] the nearest lat_longs are:
[[28.10914764 30.7516616 ]]
With distances of:
[3.4770454e-07]
-------------------------------------
Indexes of nearest lat_long [554]
For lat_long [30.29316659 30.98149914] the nearest lat_longs are:
[[30.29316659 30.98149914]]
With distances of:
[3.63890537e-07]
-----------------------------

Indexes of nearest lat_long [447]
For lat_long [30.54606958 31.18323008] the nearest lat_longs are:
[[30.54512995 31.18260863]]
With distances of:
[0.1202426]
-------------------------------------
Indexes of nearest lat_long [539]
For lat_long [30.59102957 30.897757  ] the nearest lat_longs are:
[[30.59102957 30.897757  ]]
With distances of:
[2.21382866e-07]
-------------------------------------
Indexes of nearest lat_long [550]
For lat_long [30.44343136 30.96572088] the nearest lat_longs are:
[[30.44343136 30.96572088]]
With distances of:
[4.43293853e-07]
-------------------------------------
Indexes of nearest lat_long [563]
For lat_long [30.54869599 31.14193183] the nearest lat_longs are:
[[30.54758033 31.13452329]]
With distances of:
[0.72021659]
-------------------------------------
Indexes of nearest lat_long [491]
For lat_long [30.46727999 30.93389284] the nearest lat_longs are:
[[30.46395204 30.93600555]]
With distances of:
[0.42182871]
-------------------------------------
Ind

Indexes of nearest lat_long [568]
For lat_long [30.54543199 31.16948493] the nearest lat_longs are:
[[30.54029682 31.17332252]]
With distances of:
[0.67905239]
-------------------------------------
Indexes of nearest lat_long [442]
For lat_long [30.51868673 30.88302688] the nearest lat_longs are:
[[30.46331579 30.88752245]]
With distances of:
[6.17201738]
-------------------------------------
Indexes of nearest lat_long [512]
For lat_long [30.4191318 30.8983915] the nearest lat_longs are:
[[30.41308001 30.88472717]]
With distances of:
[1.4729882]
-------------------------------------
Indexes of nearest lat_long [517]
For lat_long [30.43935205 30.90385215] the nearest lat_longs are:
[[30.4191318 30.8983915]]
With distances of:
[2.30854229]
-------------------------------------
Indexes of nearest lat_long [486]
For lat_long [30.52375008 31.04739285] the nearest lat_longs are:
[[30.54383033 31.04700979]]
With distances of:
[2.23312332]
-------------------------------------
Indexes of near

Indexes of nearest lat_long [469]
For lat_long [30.55039098 31.17483064] the nearest lat_longs are:
[[30.55039098 31.17483064]]
With distances of:
[9.57591276e-08]
-------------------------------------
Indexes of nearest lat_long [480]
For lat_long [30.55837776 31.00695643] the nearest lat_longs are:
[[30.55837775 31.00695643]]
With distances of:
[5.64159681e-07]
-------------------------------------
Indexes of nearest lat_long [446]
For lat_long [30.54823699 31.01073831] the nearest lat_longs are:
[[30.54823699 31.01073831]]
With distances of:
[4.4292026e-07]
-------------------------------------
Indexes of nearest lat_long [466]
For lat_long [30.54758033 31.13452329] the nearest lat_longs are:
[[30.54758033 31.13452329]]
With distances of:
[5.07941225e-07]
-------------------------------------
Indexes of nearest lat_long [445]
For lat_long [30.63187962 31.08070321] the nearest lat_longs are:
[[30.63187962 31.08070321]]
With distances of:
[1.46684209e-07]
-----------------------------

Indexes of nearest lat_long [716]
For lat_long [30.585769 31.482968] the nearest lat_longs are:
[[30.585769 31.482968]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [604]
For lat_long [30.585947 31.482905] the nearest lat_longs are:
[[30.585947 31.482905]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [605]
For lat_long [30.584644 31.486875] the nearest lat_longs are:
[[30.584644 31.486875]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [720]
For lat_long [30.58356  31.520278] the nearest lat_longs are:
[[30.58356  31.520278]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [607]
For lat_long [30.587932 31.472672] the nearest lat_longs are:
[[30.587932 31.472672]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [608]
For lat_long [30.586404 31.482259] the nearest lat_longs

Indexes of nearest lat_long [576]
For lat_long [30.5391071 31.6782719] the nearest lat_longs are:
[[30.53301507 31.67337145]]
With distances of:
[0.82410394]
-------------------------------------
Indexes of nearest lat_long [749]
For lat_long [30.56621681 31.44162803] the nearest lat_longs are:
[[30.59343073 31.43233596]]
With distances of:
[3.15408341]
-------------------------------------
Indexes of nearest lat_long [679]
For lat_long [30.41694642 31.56484166] the nearest lat_longs are:
[[30.42056539 31.56406853]]
With distances of:
[0.40918286]
-------------------------------------
Indexes of nearest lat_long [653]
For lat_long [30.58597609 31.50376518] the nearest lat_longs are:
[[30.58597609 31.50376518]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [653]
For lat_long [30.58597609 31.50376518] the nearest lat_longs are:
[[30.58597609 31.50376518]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long 

Indexes of nearest lat_long [581]
For lat_long [30.472337 31.464796] the nearest lat_longs are:
[[30.472337 31.464796]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [583]
For lat_long [30.665654 31.691813] the nearest lat_longs are:
[[30.665654 31.691813]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [636]
For lat_long [30.78929  31.393775] the nearest lat_longs are:
[[30.78929  31.393775]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [699]
For lat_long [30.579213 31.515986] the nearest lat_longs are:
[[30.579213 31.515986]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [634]
For lat_long [30.798202 31.628144] the nearest lat_longs are:
[[30.798202 31.628144]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [585]
For lat_long [30.44205  31.471692] the nearest lat_longs

Indexes of nearest lat_long [632]
For lat_long [30.589586 31.496186] the nearest lat_longs are:
[[30.589586 31.496186]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [599]
For lat_long [30.86191643 31.9147469 ] the nearest lat_longs are:
[[30.86291373 31.91388731]]
With distances of:
[0.1379471]
-------------------------------------
Indexes of nearest lat_long [703]
For lat_long [30.37576774 31.45051733] the nearest lat_longs are:
[[30.383747 31.458116]]
With distances of:
[1.1482767]
-------------------------------------
Indexes of nearest lat_long [732]
For lat_long [30.6147243  31.45917455] the nearest lat_longs are:
[[30.615046 31.459644]]
With distances of:
[0.0574263]
-------------------------------------
Indexes of nearest lat_long [660]
For lat_long [30.91588251 32.02038014] the nearest lat_longs are:
[[30.86221269 31.91726015]]
With distances of:
[11.50832274]
-------------------------------------
Indexes of nearest lat_long [752]
Fo

Indexes of nearest lat_long [978]
For lat_long [31.205287 29.966553] the nearest lat_longs are:
[[31.205287 29.966553]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [799]
For lat_long [31.173516 29.983599] the nearest lat_longs are:
[[31.173516 29.983599]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [800]
For lat_long [31.002804 29.804831] the nearest lat_longs are:
[[31.002804 29.804831]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [925]
For lat_long [31.20783111 29.92912785] the nearest lat_longs are:
[[31.20865258 29.93052531]]
With distances of:
[0.16126672]
-------------------------------------
Indexes of nearest lat_long [864]
For lat_long [31.237074 29.957522] the nearest lat_longs are:
[[31.24007523 29.95591113]]
With distances of:
[0.36718554]
-------------------------------------
Indexes of nearest lat_long [945]
For lat_long [31.28686809 30

Indexes of nearest lat_long [850]
For lat_long [31.200108 29.922012] the nearest lat_longs are:
[[31.200108 29.922012]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1047]
For lat_long [30.852997 29.603637] the nearest lat_longs are:
[[30.852997 29.603637]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1028]
For lat_long [31.212611 29.928514] the nearest lat_longs are:
[[31.212611 29.928514]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [837]
For lat_long [31.196528 29.896419] the nearest lat_longs are:
[[31.19715255 29.89827627]]
With distances of:
[0.18981496]
-------------------------------------
Indexes of nearest lat_long [854]
For lat_long [31.016542 29.759929] the nearest lat_longs are:
[[31.016542 29.759929]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [855]
For lat_long [31.197566 29.887215] the nea

Indexes of nearest lat_long [1084]
For lat_long [31.274764 30.005369] the nearest lat_longs are:
[[31.274764 30.005369]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1048]
For lat_long [30.866498 29.575058] the nearest lat_longs are:
[[30.866498 29.575058]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [896]
For lat_long [31.268295 29.995392] the nearest lat_longs are:
[[31.268295 29.995392]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1080]
For lat_long [31.268277 29.995406] the nearest lat_longs are:
[[31.268277 29.995406]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1005]
For lat_long [31.26992  30.024672] the nearest lat_longs are:
[[31.26992  30.024672]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [899]
For lat_long [31.214339 29.93917 ] the nearest lat_l

Indexes of nearest lat_long [3500]
For lat_long [30.96906033 28.73648847] the nearest lat_longs are:
[[30.969692 28.73747 ]]
With distances of:
[0.11700892]
-------------------------------------
Indexes of nearest lat_long [928]
For lat_long [31.20866416 30.02061591] the nearest lat_longs are:
[[31.20529165 30.02053859]]
With distances of:
[0.37507809]
-------------------------------------
Indexes of nearest lat_long [874]
For lat_long [31.12107616 29.78680833] the nearest lat_longs are:
[[31.11808371 29.79076231]]
With distances of:
[0.50238341]
-------------------------------------
Indexes of nearest lat_long [944]
For lat_long [31.24098658 29.99595906] the nearest lat_longs are:
[[31.24583989 29.99451309]]
With distances of:
[0.55689639]
-------------------------------------
Indexes of nearest lat_long [870]
For lat_long [31.27067819 29.99780476] the nearest lat_longs are:
[[31.27062994 29.99449947]]
With distances of:
[0.31418418]
-------------------------------------
Indexes of ne

Indexes of nearest lat_long [779]
For lat_long [31.31246  30.067892] the nearest lat_longs are:
[[31.31246  30.067892]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1005]
For lat_long [31.26992  30.024672] the nearest lat_longs are:
[[31.26992  30.024672]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1006]
For lat_long [30.99868  29.853873] the nearest lat_longs are:
[[30.99868  29.853873]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [884]
For lat_long [31.183138 29.878009] the nearest lat_longs are:
[[31.183138 29.878009]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1008]
For lat_long [31.316492 30.059624] the nearest lat_longs are:
[[31.316492 30.059624]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [820]
For lat_long [31.198353 29.882157] the nearest lat_lo

Indexes of nearest lat_long [1036]
For lat_long [31.18877967 30.00690169] the nearest lat_longs are:
[[31.204438 30.003317]]
With distances of:
[1.77419738]
-------------------------------------
Indexes of nearest lat_long [823]
For lat_long [31.256355 29.992169] the nearest lat_longs are:
[[31.256355 29.992169]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1059]
For lat_long [31.20744  29.920732] the nearest lat_longs are:
[[31.20744  29.920732]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1060]
For lat_long [30.974608 29.563207] the nearest lat_longs are:
[[30.974608 29.563207]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1061]
For lat_long [31.200486 29.896771] the nearest lat_longs are:
[[31.200486 29.896771]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [837]
For lat_long [31.1970895  29.89839497] t

Indexes of nearest lat_long [1102]
For lat_long [27.1838221  31.16886305] the nearest lat_longs are:
[[27.18374922 31.16880784]]
With distances of:
[0.00977213]
-------------------------------------
Indexes of nearest lat_long [1101]
For lat_long [27.18374922 31.16880784] the nearest lat_longs are:
[[27.1838221  31.16886305]]
With distances of:
[0.00977213]
-------------------------------------
Indexes of nearest lat_long [1122]
For lat_long [27.43814448 30.81668944] the nearest lat_longs are:
[[27.43921799 30.81883979]]
With distances of:
[0.24347839]
-------------------------------------
Indexes of nearest lat_long [1100]
For lat_long [27.43781146 30.8276608 ] the nearest lat_longs are:
[[27.43953532 30.8273281 ]]
With distances of:
[0.19447574]
-------------------------------------
Indexes of nearest lat_long [1131]
For lat_long [27.19207954 31.18616168] the nearest lat_longs are:
[[27.19433507 31.18660671]]
With distances of:
[0.25463682]
-------------------------------------
Index

Indexes of nearest lat_long [1123]
For lat_long [27.19633785 31.18515719] the nearest lat_longs are:
[[27.19731125 31.18581102]]
With distances of:
[0.12608283]
-------------------------------------
Indexes of nearest lat_long [1130]
For lat_long [27.18330279 31.18583587] the nearest lat_longs are:
[[27.18102219 31.18746216]]
With distances of:
[0.30030912]
-------------------------------------
Indexes of nearest lat_long [1155]
For lat_long [27.30834417 30.96605765] the nearest lat_longs are:
[[27.30827966 30.96938791]]
With distances of:
[0.32911582]
-------------------------------------
Indexes of nearest lat_long [1124]
For lat_long [27.19890094 31.18521968] the nearest lat_longs are:
[[27.19792152 31.1843331 ]]
With distances of:
[0.13981775]
-------------------------------------
Indexes of nearest lat_long [1148]
For lat_long [27.18007947 31.02266292] the nearest lat_longs are:
[[27.20343975 30.99665661]]
With distances of:
[3.65558955]
-------------------------------------
Index

Indexes of nearest lat_long [1266]
For lat_long [24.09278849 32.89647103] the nearest lat_longs are:
[[24.0920201  32.89577538]]
With distances of:
[0.11084486]
-------------------------------------
Indexes of nearest lat_long [1234]
For lat_long [24.41004134 32.92668034] the nearest lat_longs are:
[[24.41175383 32.92724376]]
With distances of:
[0.19878199]
-------------------------------------
Indexes of nearest lat_long [1227]
For lat_long [25.04230981 32.85863589] the nearest lat_longs are:
[[25.04230981 32.85863589]]
With distances of:
[2.44147853e-07]
-------------------------------------
Indexes of nearest lat_long [1252]
For lat_long [24.47928889 32.94309971] the nearest lat_longs are:
[[24.47887908 32.94377731]]
With distances of:
[0.08233365]
-------------------------------------
Indexes of nearest lat_long [1242]
For lat_long [22.34042972 31.61450623] the nearest lat_longs are:
[[22.34850694 31.61642314]]
With distances of:
[0.91952866]
-------------------------------------
I

Indexes of nearest lat_long [1211]
For lat_long [24.10006523 32.9004554 ] the nearest lat_longs are:
[[24.09921611 32.89901099]]
With distances of:
[0.17438355]
-------------------------------------
Indexes of nearest lat_long [1237]
For lat_long [24.93281738 32.9027742 ] the nearest lat_longs are:
[[24.92676127 32.8580406 ]]
With distances of:
[4.56067315]
-------------------------------------
Indexes of nearest lat_long [1234]
For lat_long [24.44736427 32.91654938] the nearest lat_longs are:
[[24.41175383 32.92724376]]
With distances of:
[4.10505252]
-------------------------------------
Indexes of nearest lat_long [1219]
For lat_long [24.54158392 33.035257  ] the nearest lat_longs are:
[[24.54155444 33.03492729]]
With distances of:
[0.03351057]
-------------------------------------
Indexes of nearest lat_long [1186]
For lat_long [24.41175383 32.92724376] the nearest lat_longs are:
[[24.41004134 32.92668034]]
With distances of:
[0.19878199]
-------------------------------------
Index

Indexes of nearest lat_long [1270]
For lat_long [23.963547 32.824228] the nearest lat_longs are:
[[23.97084113 32.87758559]]
With distances of:
[5.48186428]
-------------------------------------
Indexes of nearest lat_long [1213]
For lat_long [24.4780657  32.94722857] the nearest lat_longs are:
[[24.47661505 32.94787025]]
With distances of:
[0.17388556]
-------------------------------------
Indexes of nearest lat_long [1194]
For lat_long [24.63160913 32.9488385 ] the nearest lat_longs are:
[[24.63108694 32.9488603 ]]
With distances of:
[0.05810622]
-------------------------------------
Indexes of nearest lat_long [3426]
For lat_long [25.15474229 32.71957615] the nearest lat_longs are:
[[25.20881756 32.65245529]]
With distances of:
[9.04289417]
-------------------------------------
Indexes of nearest lat_long [1296]
For lat_long [28.82091688 30.90268724] the nearest lat_longs are:
[[28.82095926 30.90270962]]
With distances of:
[0.00519159]
-------------------------------------
Indexes o

Indexes of nearest lat_long [1323]
For lat_long [29.2001896  31.16251954] the nearest lat_longs are:
[[29.237013 31.191731]]
With distances of:
[4.9801705]
-------------------------------------
Indexes of nearest lat_long [1277]
For lat_long [28.92750875 30.98734427] the nearest lat_longs are:
[[28.927984 30.9867  ]]
With distances of:
[0.0820004]
-------------------------------------
Indexes of nearest lat_long [1333]
For lat_long [29.07295458 31.11286507] the nearest lat_longs are:
[[29.074015 31.115   ]]
With distances of:
[0.23864614]
-------------------------------------
Indexes of nearest lat_long [1286]
For lat_long [29.35714367 31.20255485] the nearest lat_longs are:
[[29.347493 31.203995]]
With distances of:
[1.08214503]
-------------------------------------
Indexes of nearest lat_long [1342]
For lat_long [29.37069224 31.17482108] the nearest lat_longs are:
[[29.3974957 31.1825006]]
With distances of:
[3.07188399]
-------------------------------------
Indexes of nearest lat_lo

Indexes of nearest lat_long [2295]
For lat_long [29.84257  31.304645] the nearest lat_longs are:
[[29.84257  31.304645]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1373]
For lat_long [30.107258 31.296789] the nearest lat_longs are:
[[30.107258 31.296789]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2076]
For lat_long [30.068299 31.230263] the nearest lat_longs are:
[[30.068299 31.230263]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1375]
For lat_long [30.0684   31.230328] the nearest lat_longs are:
[[30.0684   31.230328]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2181]
For lat_long [30.119142 31.389656] the nearest lat_longs are:
[[30.119142 31.389656]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1378]
For lat_long [30.063531 31.235202] the nearest lat

Indexes of nearest lat_long [1427]
For lat_long [30.127452 31.401412] the nearest lat_longs are:
[[30.12762472 31.40244492]]
With distances of:
[0.10117934]
-------------------------------------
Indexes of nearest lat_long [1780]
For lat_long [30.11411  31.396824] the nearest lat_longs are:
[[30.113739 31.395544]]
With distances of:
[0.12984675]
-------------------------------------
Indexes of nearest lat_long [1425]
For lat_long [30.12762472 31.40244492] the nearest lat_longs are:
[[30.127452 31.401412]]
With distances of:
[0.10117934]
-------------------------------------
Indexes of nearest lat_long [1427]
For lat_long [30.12853  31.403166] the nearest lat_longs are:
[[30.12762472 31.40244492]]
With distances of:
[0.12223812]
-------------------------------------
Indexes of nearest lat_long [1430]
For lat_long [30.128063 31.399607] the nearest lat_longs are:
[[30.127897 31.399315]]
With distances of:
[0.03360568]
-------------------------------------
Indexes of nearest lat_long [1429

Indexes of nearest lat_long [1623]
For lat_long [30.056804 31.239295] the nearest lat_longs are:
[[30.05662272 31.23870944]]
With distances of:
[0.05985267]
-------------------------------------
Indexes of nearest lat_long [1480]
For lat_long [30.061185 31.332125] the nearest lat_longs are:
[[30.061185 31.332125]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2134]
For lat_long [30.068236 31.329351] the nearest lat_longs are:
[[30.068236 31.329351]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2143]
For lat_long [29.980378 31.325083] the nearest lat_longs are:
[[29.980378 31.325083]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1726]
For lat_long [29.84862106 31.33290654] the nearest lat_longs are:
[[29.849069 31.334194]]
With distances of:
[0.13378557]
-------------------------------------
Indexes of nearest lat_long [1484]
For lat_long [30.104774 31

Indexes of nearest lat_long [1534]
For lat_long [29.864626 31.332533] the nearest lat_longs are:
[[29.864626 31.332533]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2304]
For lat_long [29.86451 31.33254] the nearest lat_longs are:
[[29.86451 31.33254]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1536]
For lat_long [30.139503 31.326609] the nearest lat_longs are:
[[30.139503 31.326609]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2230]
For lat_long [30.068912 31.342072] the nearest lat_longs are:
[[30.068404   31.34269332]]
With distances of:
[0.08225359]
-------------------------------------
Indexes of nearest lat_long [1538]
For lat_long [30.080954 31.334259] the nearest lat_longs are:
[[30.080954 31.334259]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1539]
For lat_long [30.062789 31.360657] the nea

Indexes of nearest lat_long [1874]
For lat_long [30.06906531 31.34331487] the nearest lat_longs are:
[[30.06865  31.343462]]
With distances of:
[0.04830172]
-------------------------------------
Indexes of nearest lat_long [2027]
For lat_long [30.06124104 31.22764582] the nearest lat_longs are:
[[30.063852 31.227839]]
With distances of:
[0.29091955]
-------------------------------------
Indexes of nearest lat_long [1835]
For lat_long [30.15894052 31.47104474] the nearest lat_longs are:
[[30.158948 31.470908]]
With distances of:
[0.01317296]
-------------------------------------
Indexes of nearest lat_long [1411]
For lat_long [29.99406533 31.29640519] the nearest lat_longs are:
[[29.987265 31.304763]]
With distances of:
[1.10438433]
-------------------------------------
Indexes of nearest lat_long [1364]
For lat_long [30.0992894  31.32447137] the nearest lat_longs are:
[[30.09596822 31.32519342]]
With distances of:
[0.37577436]
-------------------------------------
Indexes of nearest la

Indexes of nearest lat_long [1876]
For lat_long [30.04149503 31.23542674] the nearest lat_longs are:
[[30.042687 31.235178]]
With distances of:
[0.13468681]
-------------------------------------
Indexes of nearest lat_long [1370]
For lat_long [30.03636734 31.25181183] the nearest lat_longs are:
[[30.03775884 31.24960743]]
With distances of:
[0.26261865]
-------------------------------------
Indexes of nearest lat_long [1796]
For lat_long [29.95880352 31.25949339] the nearest lat_longs are:
[[29.959583 31.258724]]
With distances of:
[0.1140454]
-------------------------------------
Indexes of nearest lat_long [2140]
For lat_long [30.0610421  31.21761008] the nearest lat_longs are:
[[30.0621136  31.21649913]]
With distances of:
[0.16008317]
-------------------------------------
Indexes of nearest lat_long [1564]
For lat_long [30.05101915 31.39503707] the nearest lat_longs are:
[[30.050807 31.393329]]
With distances of:
[0.16608284]
-------------------------------------
Indexes of nearest

Indexes of nearest lat_long [2349]
For lat_long [30.097703 31.245179] the nearest lat_longs are:
[[30.097703 31.245179]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2199]
For lat_long [30.077271 31.277646] the nearest lat_longs are:
[[30.077271 31.277646]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1703]
For lat_long [29.994952 31.231662] the nearest lat_longs are:
[[29.994952 31.231662]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2095]
For lat_long [30.044179 31.234499] the nearest lat_longs are:
[[30.044179 31.234499]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1705]
For lat_long [30.029405 31.235348] the nearest lat_longs are:
[[30.029405 31.235348]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1706]
For lat_long [30.061171 31.24572 ] the nearest lat

Indexes of nearest lat_long [2366]
For lat_long [29.87923  31.313375] the nearest lat_longs are:
[[29.87923  31.313375]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1758]
For lat_long [29.842563 31.375574] the nearest lat_longs are:
[[29.842563 31.375574]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1759]
For lat_long [30.062773 31.246209] the nearest lat_longs are:
[[30.062773 31.246209]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1760]
For lat_long [30.053973 31.255965] the nearest lat_longs are:
[[30.053973 31.255965]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1761]
For lat_long [30.006031 31.426481] the nearest lat_longs are:
[[30.006031 31.426481]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2123]
For lat_long [30.053249 31.239341] the nearest lat

Indexes of nearest lat_long [2070]
For lat_long [30.04900944 31.24422502] the nearest lat_longs are:
[[30.048966 31.244224]]
With distances of:
[0.00483098]
-------------------------------------
Indexes of nearest lat_long [2081]
For lat_long [30.071591 31.288335] the nearest lat_longs are:
[[30.071591 31.288335]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1815]
For lat_long [30.071543 31.288413] the nearest lat_longs are:
[[30.071543 31.288413]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1894]
For lat_long [30.066363 31.285149] the nearest lat_longs are:
[[30.066363 31.285149]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2049]
For lat_long [30.066387 31.285174] the nearest lat_longs are:
[[30.066387 31.285174]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2279]
For lat_long [30.024583 31.241886] the

Indexes of nearest lat_long [2044]
For lat_long [30.048133 31.309555] the nearest lat_longs are:
[[30.048133 31.309555]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1415]
For lat_long [30.067815 31.216579] the nearest lat_longs are:
[[30.0686343 31.217789 ]]
With distances of:
[0.14784394]
-------------------------------------
Indexes of nearest lat_long [1860]
For lat_long [29.877955 31.288686] the nearest lat_longs are:
[[29.877955 31.288686]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1416]
For lat_long [30.03220063 31.23208748] the nearest lat_longs are:
[[30.034433 31.234171]]
With distances of:
[0.31913312]
-------------------------------------
Indexes of nearest lat_long [1617]
For lat_long [30.052786 31.273161] the nearest lat_longs are:
[[30.05237949 31.27499391]]
With distances of:
[0.18211054]
-------------------------------------
Indexes of nearest lat_long [1863]
For lat_long [30

Indexes of nearest lat_long [1587]
For lat_long [29.82733789 31.36639024] the nearest lat_longs are:
[[29.82874569 31.36742056]]
With distances of:
[0.18542683]
-------------------------------------
Indexes of nearest lat_long [1389]
For lat_long [30.0463229  31.25404872] the nearest lat_longs are:
[[30.04731002 31.25455458]]
With distances of:
[0.12007706]
-------------------------------------
Indexes of nearest lat_long [1920]
For lat_long [30.10873403 31.29249034] the nearest lat_longs are:
[[30.10663389 31.28858172]]
With distances of:
[0.44260159]
-------------------------------------
Indexes of nearest lat_long [2257]
For lat_long [29.97699459 31.35831075] the nearest lat_longs are:
[[29.98573  31.357187]]
With distances of:
[0.97734492]
-------------------------------------
Indexes of nearest lat_long [1486]
For lat_long [30.04601319 31.27115973] the nearest lat_longs are:
[[30.045986 31.270861]]
With distances of:
[0.02891216]
-------------------------------------
Indexes of ne

Indexes of nearest lat_long [1702]
For lat_long [30.07788239 31.27447615] the nearest lat_longs are:
[[30.077271 31.277646]]
With distances of:
[0.31249471]
-------------------------------------
Indexes of nearest lat_long [1418]
For lat_long [29.85008854 31.32524469] the nearest lat_longs are:
[[29.847929 31.328819]]
With distances of:
[0.42011225]
-------------------------------------
Indexes of nearest lat_long [1728]
For lat_long [29.98147218 31.24124195] the nearest lat_longs are:
[[29.981863 31.242316]]
With distances of:
[0.11220485]
-------------------------------------
Indexes of nearest lat_long [2116]
For lat_long [29.98464498 31.24304176] the nearest lat_longs are:
[[29.984219 31.246047]]
With distances of:
[0.29329302]
-------------------------------------
Indexes of nearest lat_long [1547]
For lat_long [30.08415351 31.23464369] the nearest lat_longs are:
[[30.081699 31.236658]]
With distances of:
[0.33474314]
-------------------------------------
Indexes of nearest lat_lo

Indexes of nearest lat_long [1491]
For lat_long [30.08368311 31.30966609] the nearest lat_longs are:
[[30.081559 31.306701]]
With distances of:
[0.37037549]
-------------------------------------
Indexes of nearest lat_long [2126]
For lat_long [30.00652241 31.24911846] the nearest lat_longs are:
[[30.002444 31.243505]]
With distances of:
[0.70557972]
-------------------------------------
Indexes of nearest lat_long [2390]
For lat_long [30.01571569 31.22335074] the nearest lat_longs are:
[[30.01342367 31.22411475]]
With distances of:
[0.26526483]
-------------------------------------
Indexes of nearest lat_long [1626]
For lat_long [29.98392836 31.23075394] the nearest lat_longs are:
[[29.97608444 31.23443557]]
With distances of:
[0.94153238]
-------------------------------------
Indexes of nearest lat_long [1448]
For lat_long [30.115871 31.393739] the nearest lat_longs are:
[[30.115871 31.393739]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [

Indexes of nearest lat_long [1456]
For lat_long [30.020047 31.466243] the nearest lat_longs are:
[[30.020047 31.466243]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1794]
For lat_long [30.068125 31.349121] the nearest lat_longs are:
[[30.068125 31.349121]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1450]
For lat_long [30.0936   31.274803] the nearest lat_longs are:
[[30.0936   31.274803]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1651]
For lat_long [30.07534 31.2286 ] the nearest lat_longs are:
[[30.071783 31.227447]]
With distances of:
[0.41078703]
-------------------------------------
Indexes of nearest lat_long [1813]
For lat_long [30.048966 31.244224] the nearest lat_longs are:
[[30.04900944 31.24422502]]
With distances of:
[0.00483098]
-------------------------------------
Indexes of nearest lat_long [1679]
For lat_long [30.061023 31.41837

Indexes of nearest lat_long [2123]
For lat_long [30.053249 31.239341] the nearest lat_longs are:
[[30.053249 31.239341]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1498]
For lat_long [30.073913 31.343591] the nearest lat_longs are:
[[30.073913 31.343591]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2125]
For lat_long [29.971479 31.399367] the nearest lat_longs are:
[[29.971479 31.399367]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1506]
For lat_long [30.002444 31.243505] the nearest lat_longs are:
[[30.002444 31.243505]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2127]
For lat_long [30.067097 31.227197] the nearest lat_longs are:
[[30.067097 31.227197]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2128]
For lat_long [30.031582 31.243677] the nearest lat

Indexes of nearest lat_long [2334]
For lat_long [30.06490018 31.53883243] the nearest lat_longs are:
[[30.07019  31.519106]]
With distances of:
[1.9873544]
-------------------------------------
Indexes of nearest lat_long [1963]
For lat_long [30.138907 31.464961] the nearest lat_longs are:
[[30.13517242 31.45545942]]
With distances of:
[1.00365261]
-------------------------------------
Indexes of nearest lat_long [2180]
For lat_long [30.121441 31.401813] the nearest lat_longs are:
[[30.121441 31.401813]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2181]
For lat_long [30.119142 31.389656] the nearest lat_longs are:
[[30.119142 31.389656]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2166]
For lat_long [30.14727735 31.60715008] the nearest lat_longs are:
[[30.15118973 31.6115737 ]]
With distances of:
[0.60841838]
-------------------------------------
Indexes of nearest lat_long [1731]
For lat_lon

Indexes of nearest lat_long [2229]
For lat_long [30.07779551 31.28486159] the nearest lat_longs are:
[[30.07851404 31.28506579]]
With distances of:
[0.08227743]
-------------------------------------
Indexes of nearest lat_long [1864]
For lat_long [30.0551702 31.3800279] the nearest lat_longs are:
[[30.052837 31.378348]]
With distances of:
[0.30569638]
-------------------------------------
Indexes of nearest lat_long [2240]
For lat_long [30.07759183 31.28635828] the nearest lat_longs are:
[[30.077141 31.287004]]
With distances of:
[0.0798342]
-------------------------------------
Indexes of nearest lat_long [1999]
For lat_long [30.051471 31.397258] the nearest lat_longs are:
[[30.05147142 31.39725793]]
With distances of:
[4.71853395e-05]
-------------------------------------
Indexes of nearest lat_long [1783]
For lat_long [29.84877916 31.33900263] the nearest lat_longs are:
[[29.852085 31.338707]]
With distances of:
[0.36869668]
-------------------------------------
Indexes of nearest l

Indexes of nearest lat_long [1687]
For lat_long [30.057156 31.225345] the nearest lat_longs are:
[[30.057156 31.225345]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1768]
For lat_long [30.169398 31.457406] the nearest lat_longs are:
[[30.169398 31.457406]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2295]
For lat_long [29.84257  31.304645] the nearest lat_longs are:
[[29.84257  31.304645]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2296]
For lat_long [30.066169 31.279672] the nearest lat_longs are:
[[30.066169 31.279672]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2297]
For lat_long [30.053195 31.239529] the nearest lat_longs are:
[[30.053195 31.239529]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2298]
For lat_long [30.04739  31.223963] the nearest lat

Indexes of nearest lat_long [2349]
For lat_long [30.097703 31.245179] the nearest lat_longs are:
[[30.097703 31.245179]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2350]
For lat_long [30.050854 31.379461] the nearest lat_longs are:
[[30.050854 31.379461]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1843]
For lat_long [30.020854 31.495367] the nearest lat_longs are:
[[30.020854 31.495367]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1543]
For lat_long [30.127901 31.320934] the nearest lat_longs are:
[[30.127901 31.320934]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1735]
For lat_long [29.946744 31.272954] the nearest lat_longs are:
[[29.946744 31.272954]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1750]
For lat_long [30.0711   31.245006] the nearest lat

Indexes of nearest lat_long [2484]
For lat_long [31.032687 31.369625] the nearest lat_longs are:
[[31.032111 31.372741]]
With distances of:
[0.30372323]
-------------------------------------
Indexes of nearest lat_long [2587]
For lat_long [31.120718 31.646416] the nearest lat_longs are:
[[31.120718 31.646416]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2607]
For lat_long [31.119647 31.447351] the nearest lat_longs are:
[[31.119647 31.447351]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2446]
For lat_long [31.18519444 32.03277334] the nearest lat_longs are:
[[31.184051 32.034273]]
With distances of:
[0.19109583]
-------------------------------------
Indexes of nearest lat_long [2410]
For lat_long [30.843289 31.312942] the nearest lat_longs are:
[[30.843289 31.312942]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2499]
For lat_long [31.15821811 31.9

Indexes of nearest lat_long [2499]
For lat_long [31.160863 31.934843] the nearest lat_longs are:
[[31.158743  31.9355969]]
With distances of:
[0.24640647]
-------------------------------------
Indexes of nearest lat_long [2513]
For lat_long [30.866844 31.282408] the nearest lat_longs are:
[[30.86684431 31.28240765]]
With distances of:
[4.80017293e-05]
-------------------------------------
Indexes of nearest lat_long [2636]
For lat_long [31.0397   31.368715] the nearest lat_longs are:
[[31.0397   31.368715]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2464]
For lat_long [31.040754 31.381102] the nearest lat_longs are:
[[31.042824 31.37839 ]]
With distances of:
[0.34603072]
-------------------------------------
Indexes of nearest lat_long [2464]
For lat_long [31.042824 31.37839 ] the nearest lat_longs are:
[[31.042824 31.37839 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2465]
For lat_long [31

Indexes of nearest lat_long [2498]
For lat_long [31.1297027 31.4219936] the nearest lat_longs are:
[[31.12152859 31.44418088]]
With distances of:
[2.29922064]
-------------------------------------
Indexes of nearest lat_long [2496]
For lat_long [30.72166318 31.25417092] the nearest lat_longs are:
[[30.72027286 31.25607253]]
With distances of:
[0.23862627]
-------------------------------------
Indexes of nearest lat_long [2628]
For lat_long [31.03155235 31.39327318] the nearest lat_longs are:
[[31.033786 31.395132]]
With distances of:
[0.30504966]
-------------------------------------
Indexes of nearest lat_long [2414]
For lat_long [30.79208093 31.35398819] the nearest lat_longs are:
[[30.767432 31.346599]]
With distances of:
[2.83027973]
-------------------------------------
Indexes of nearest lat_long [2487]
For lat_long [30.71339125 31.26236442] the nearest lat_longs are:
[[30.720512 31.260394]]
With distances of:
[0.81388779]
-------------------------------------
Indexes of nearest 

Indexes of nearest lat_long [2523]
For lat_long [31.14424252 31.71973764] the nearest lat_longs are:
[[31.14496486 31.71208188]]
With distances of:
[0.73299593]
-------------------------------------
Indexes of nearest lat_long [2676]
For lat_long [31.24943875 31.64883691] the nearest lat_longs are:
[[31.23937202 31.64907738]]
With distances of:
[1.11960272]
-------------------------------------
Indexes of nearest lat_long [2401]
For lat_long [31.0952708 31.3046842] the nearest lat_longs are:
[[31.09863  31.306596]]
With distances of:
[0.41552107]
-------------------------------------
Indexes of nearest lat_long [2455]
For lat_long [31.16192766 31.81484204] the nearest lat_longs are:
[[31.167388 31.803124]]
With distances of:
[1.26954584]
-------------------------------------
Indexes of nearest lat_long [2567]
For lat_long [31.00316718 31.39776226] the nearest lat_longs are:
[[31.0239742  31.39927298]]
With distances of:
[2.31811014]
-------------------------------------
Indexes of near

Indexes of nearest lat_long [2470]
For lat_long [31.180477 31.965242] the nearest lat_longs are:
[[31.180477 31.965242]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2615]
For lat_long [31.021598 31.64903 ] the nearest lat_longs are:
[[31.021598 31.64903 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2450]
For lat_long [31.025265 31.644631] the nearest lat_longs are:
[[31.025265 31.644631]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2480]
For lat_long [31.182237 32.033809] the nearest lat_longs are:
[[31.182237 32.033809]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2618]
For lat_long [31.089528 31.60074 ] the nearest lat_longs are:
[[31.089528 31.60074 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2446]
For lat_long [31.184051 32.034273] the nearest lat

Indexes of nearest lat_long [2646]
For lat_long [31.421382 31.805752] the nearest lat_longs are:
[[31.42742  31.803943]]
With distances of:
[0.69298947]
-------------------------------------
Indexes of nearest lat_long [2661]
For lat_long [31.2906   31.677441] the nearest lat_longs are:
[[31.245079 31.679219]]
With distances of:
[5.06452435]
-------------------------------------
Indexes of nearest lat_long [2679]
For lat_long [31.372934 31.521293] the nearest lat_longs are:
[[31.36055974 31.57138945]]
With distances of:
[4.95138834]
-------------------------------------
Indexes of nearest lat_long [2558]
For lat_long [31.245079 31.679219] the nearest lat_longs are:
[[31.24943875 31.64883691]]
With distances of:
[2.9286636]
-------------------------------------
Indexes of nearest lat_long [2663]
For lat_long [31.434946 31.801476] the nearest lat_longs are:
[[31.434963 31.8016  ]]
With distances of:
[0.01191542]
-------------------------------------
Indexes of nearest lat_long [2662]
For

Indexes of nearest lat_long [2761]
For lat_long [30.00372314 31.17326819] the nearest lat_longs are:
[[29.99898  31.172662]]
With distances of:
[0.53063423]
-------------------------------------
Indexes of nearest lat_long [2916]
For lat_long [29.99378633 31.1606346 ] the nearest lat_longs are:
[[29.99567936 31.16387222]]
With distances of:
[0.37619456]
-------------------------------------
Indexes of nearest lat_long [3183]
For lat_long [30.075121 31.013411] the nearest lat_longs are:
[[30.075121 31.013411]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3139]
For lat_long [30.069952 31.019785] the nearest lat_longs are:
[[30.069952 31.019785]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3128]
For lat_long [29.947265 30.88849 ] the nearest lat_longs are:
[[29.947265 30.88849 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2706]
For lat_long [29.99412

Indexes of nearest lat_long [3108]
For lat_long [30.00072  31.166831] the nearest lat_longs are:
[[30.00072  31.166831]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2755]
For lat_long [30.039508 31.205899] the nearest lat_longs are:
[[30.039508 31.205899]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2690]
For lat_long [30.0149752  31.21212728] the nearest lat_longs are:
[[30.01475112 31.21099606]]
With distances of:
[0.11173128]
-------------------------------------
Indexes of nearest lat_long [2934]
For lat_long [29.898783 31.277826] the nearest lat_longs are:
[[29.89878323 31.2778261 ]]
With distances of:
[2.73311796e-05]
-------------------------------------
Indexes of nearest lat_long [2931]
For lat_long [29.899543 31.270184] the nearest lat_longs are:
[[29.89954286 31.27018426]]
With distances of:
[2.95038804e-05]
-------------------------------------
Indexes of nearest lat_long [3161]
Fo

Indexes of nearest lat_long [2895]
For lat_long [29.97190459 31.01640637] the nearest lat_longs are:
[[29.971776 31.014622]]
With distances of:
[0.17247275]
-------------------------------------
Indexes of nearest lat_long [3016]
For lat_long [29.98118568 30.94950643] the nearest lat_longs are:
[[29.98258424 30.95334044]]
With distances of:
[0.40068374]
-------------------------------------
Indexes of nearest lat_long [3182]
For lat_long [30.06035869 31.20371686] the nearest lat_longs are:
[[30.060424 31.203553]]
With distances of:
[0.0173615]
-------------------------------------
Indexes of nearest lat_long [2812]
For lat_long [30.058952 31.207427] the nearest lat_longs are:
[[30.058952 31.207427]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2813]
For lat_long [30.061344 31.207382] the nearest lat_longs are:
[[30.061344 31.207382]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2814]
For lat_lon

Indexes of nearest lat_long [3103]
For lat_long [30.031977 31.003541] the nearest lat_longs are:
[[30.031977 31.003541]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3134]
For lat_long [29.994362 31.203248] the nearest lat_longs are:
[[29.994362 31.203248]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3126]
For lat_long [30.121953 31.14071 ] the nearest lat_longs are:
[[30.121953 31.14071 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2868]
For lat_long [29.949398 30.912739] the nearest lat_longs are:
[[29.949398 30.912739]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2869]
For lat_long [29.853307 31.278523] the nearest lat_longs are:
[[29.853307 31.278523]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2870]
For lat_long [29.887683 31.273272] the nearest lat

Indexes of nearest lat_long [2987]
For lat_long [29.98291711 31.14312655] the nearest lat_longs are:
[[29.98179579 31.1471299 ]]
With distances of:
[0.40524015]
-------------------------------------
Indexes of nearest lat_long [2815]
For lat_long [29.99960702 31.17632661] the nearest lat_longs are:
[[29.999607 31.176327]]
With distances of:
[3.76220116e-05]
-------------------------------------
Indexes of nearest lat_long [2960]
For lat_long [30.01979798 31.0023935 ] the nearest lat_longs are:
[[30.02013876 31.00446783]]
With distances of:
[0.20327594]
-------------------------------------
Indexes of nearest lat_long [3021]
For lat_long [29.98750485 31.16467565] the nearest lat_longs are:
[[29.9856732 31.1684829]]
With distances of:
[0.41944583]
-------------------------------------
Indexes of nearest lat_long [2993]
For lat_long [30.00678328 31.1949822 ] the nearest lat_longs are:
[[30.00829614 31.19906493]]
With distances of:
[0.42760715]
-------------------------------------
Indexes

Indexes of nearest lat_long [3153]
For lat_long [29.95115737 30.91264052] the nearest lat_longs are:
[[29.949398 30.912739]]
With distances of:
[0.19586297]
-------------------------------------
Indexes of nearest lat_long [3140]
For lat_long [29.96893724 30.92278106] the nearest lat_longs are:
[[29.963594 30.925925]]
With distances of:
[0.6668778]
-------------------------------------
Indexes of nearest lat_long [2794]
For lat_long [29.97071117 30.95029192] the nearest lat_longs are:
[[29.965099 30.950843]]
With distances of:
[0.62629861]
-------------------------------------
Indexes of nearest lat_long [2732]
For lat_long [29.93694093 30.89649811] the nearest lat_longs are:
[[29.939706 30.890616]]
With distances of:
[0.64480844]
-------------------------------------
Indexes of nearest lat_long [3153]
For lat_long [29.9424403 30.9186961] the nearest lat_longs are:
[[29.949398 30.912739]]
With distances of:
[0.96332204]
-------------------------------------
Indexes of nearest lat_long 

Indexes of nearest lat_long [3060]
For lat_long [29.45727965 31.21232928] the nearest lat_longs are:
[[29.459579 31.260741]]
With distances of:
[4.69413466]
-------------------------------------
Indexes of nearest lat_long [3010]
For lat_long [29.99956174 31.16025742] the nearest lat_longs are:
[[29.99818228 31.15960493]]
With distances of:
[0.1657597]
-------------------------------------
Indexes of nearest lat_long [2915]
For lat_long [30.03723059 30.98646969] the nearest lat_longs are:
[[30.04481693 30.98976025]]
With distances of:
[0.90106784]
-------------------------------------
Indexes of nearest lat_long [3008]
For lat_long [29.99818228 31.15960493] the nearest lat_longs are:
[[29.99956174 31.16025742]]
With distances of:
[0.1657597]
-------------------------------------
Indexes of nearest lat_long [3011]
For lat_long [30.063993 31.025685] the nearest lat_longs are:
[[30.063993 31.025685]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long

Indexes of nearest lat_long [2853]
For lat_long [30.00834  31.176454] the nearest lat_longs are:
[[30.00834  31.176454]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2783]
For lat_long [30.039886 31.21771 ] the nearest lat_longs are:
[[30.039886 31.21771 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2739]
For lat_long [30.038749 31.058416] the nearest lat_longs are:
[[30.038749 31.058416]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2838]
For lat_long [30.035836 31.199983] the nearest lat_longs are:
[[30.035836 31.199983]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2962]
For lat_long [30.064286 31.024813] the nearest lat_longs are:
[[30.06482005 31.02539484]]
With distances of:
[0.08161906]
-------------------------------------
Indexes of nearest lat_long [2840]
For lat_long [30.038341 31.212192] the

Indexes of nearest lat_long [3120]
For lat_long [30.011197 31.185411] the nearest lat_longs are:
[[30.011197 31.185411]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2789]
For lat_long [30.05656  30.947515] the nearest lat_longs are:
[[30.05656  30.947515]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2768]
For lat_long [29.992626 31.12923 ] the nearest lat_longs are:
[[29.992626 31.12923 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3123]
For lat_long [29.975969 30.94448 ] the nearest lat_longs are:
[[29.975969 30.94448 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3124]
For lat_long [30.050112 31.209817] the nearest lat_longs are:
[[30.050112 31.209817]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3125]
For lat_long [30.0505   30.996935] the nearest lat

Indexes of nearest lat_long [3177]
For lat_long [30.071119 31.020786] the nearest lat_longs are:
[[30.071119 31.020786]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2760]
For lat_long [30.040862 31.210587] the nearest lat_longs are:
[[30.040862 31.210587]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3179]
For lat_long [30.043236 31.210047] the nearest lat_longs are:
[[30.043236 31.210047]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3180]
For lat_long [30.068506 31.023747] the nearest lat_longs are:
[[30.068506 31.023747]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2688]
For lat_long [30.062593 31.205734] the nearest lat_longs are:
[[30.062593 31.205734]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [2898]
For lat_long [30.060424 31.203553] the nearest lat

Indexes of nearest lat_long [3303]
For lat_long [30.58657086 32.28681588] the nearest lat_longs are:
[[30.58657086 32.28681588]]
With distances of:
[3.33596264e-07]
-------------------------------------
Indexes of nearest lat_long [3312]
For lat_long [30.58400056 32.25732386] the nearest lat_longs are:
[[30.58400056 32.25732386]]
With distances of:
[2.21392192e-07]
-------------------------------------
Indexes of nearest lat_long [3294]
For lat_long [30.31524412 32.30583565] the nearest lat_longs are:
[[30.31524412 32.30583565]]
With distances of:
[3.84893156e-07]
-------------------------------------
Indexes of nearest lat_long [3283]
For lat_long [30.58918082 32.28252052] the nearest lat_longs are:
[[30.58918082 32.28252052]]
With distances of:
[3.84610317e-07]
-------------------------------------
Indexes of nearest lat_long [3311]
For lat_long [30.58466539 32.27117259] the nearest lat_longs are:
[[30.58466539 32.27117259]]
With distances of:
[4.44779743e-07]
-----------------------

Indexes of nearest lat_long [3224]
For lat_long [30.59070604 32.29670406] the nearest lat_longs are:
[[30.59070604 32.29670406]]
With distances of:
[5.88010721e-07]
-------------------------------------
Indexes of nearest lat_long [3218]
For lat_long [30.59723489 32.27151054] the nearest lat_longs are:
[[30.59723489 32.27151054]]
With distances of:
[2.93421474e-07]
-------------------------------------
Indexes of nearest lat_long [3239]
For lat_long [30.56675659 31.93504299] the nearest lat_longs are:
[[30.56675659 31.93504299]]
With distances of:
[5.29461503e-07]
-------------------------------------
Indexes of nearest lat_long [3223]
For lat_long [30.5967759  32.26337629] the nearest lat_longs are:
[[30.5967759  32.26337629]]
With distances of:
[3.63197341e-07]
-------------------------------------
Indexes of nearest lat_long [3217]
For lat_long [30.62205351 32.26923448] the nearest lat_longs are:
[[30.62205351 32.26923448]]
With distances of:
[1.46699152e-07]
-----------------------

Indexes of nearest lat_long [3376]
For lat_long [31.11415776 30.94230175] the nearest lat_longs are:
[[31.113927 30.941891]]
With distances of:
[0.04676956]
-------------------------------------
Indexes of nearest lat_long [3322]
For lat_long [31.29008495 30.52348558] the nearest lat_longs are:
[[31.28994018 30.52365427]]
With distances of:
[0.02271693]
-------------------------------------
Indexes of nearest lat_long [3321]
For lat_long [31.28994018 30.52365427] the nearest lat_longs are:
[[31.29008495 30.52348558]]
With distances of:
[0.02271693]
-------------------------------------
Indexes of nearest lat_long [3326]
For lat_long [31.13192139 30.64373631] the nearest lat_longs are:
[[31.12859394 30.64141709]]
With distances of:
[0.4308445]
-------------------------------------
Indexes of nearest lat_long [3372]
For lat_long [31.2706038  30.78453445] the nearest lat_longs are:
[[31.27167024 30.78420579]]
With distances of:
[0.1226278]
-------------------------------------
Indexes of 

Indexes of nearest lat_long [3364]
For lat_long [31.30231766 30.52177694] the nearest lat_longs are:
[[31.2923283  30.52485725]]
With distances of:
[1.14867798]
-------------------------------------
Indexes of nearest lat_long [3325]
For lat_long [31.17591009 31.22748937] the nearest lat_longs are:
[[31.17400503 31.22401906]]
With distances of:
[0.39226975]
-------------------------------------
Indexes of nearest lat_long [3345]
For lat_long [31.04856396 30.85440033] the nearest lat_longs are:
[[31.04748246 30.8501427 ]]
With distances of:
[0.42305416]
-------------------------------------
Indexes of nearest lat_long [3346]
For lat_long [31.08940784 30.94456216] the nearest lat_longs are:
[[31.10743053 30.94190183]]
With distances of:
[2.01997608]
-------------------------------------
Indexes of nearest lat_long [3335]
For lat_long [31.55234113 31.09106729] the nearest lat_longs are:
[[31.55265909 31.09060061]]
With distances of:
[0.05661637]
-------------------------------------
Index

Indexes of nearest lat_long [3491]
For lat_long [25.68770931 32.63176044] the nearest lat_longs are:
[[25.68770931 32.63176044]]
With distances of:
[5.21483681e-07]
-------------------------------------
Indexes of nearest lat_long [3457]
For lat_long [25.6655911 32.6239013] the nearest lat_longs are:
[[25.6655911 32.6239013]]
With distances of:
[5.98788009e-07]
-------------------------------------
Indexes of nearest lat_long [3478]
For lat_long [25.69450397 32.64000109] the nearest lat_longs are:
[[25.69116357 32.64074258]]
With distances of:
[0.37879402]
-------------------------------------
Indexes of nearest lat_long [3412]
For lat_long [25.70544947 32.63454947] the nearest lat_longs are:
[[25.70764694 32.64401769]]
With distances of:
[0.97958193]
-------------------------------------
Indexes of nearest lat_long [3490]
For lat_long [25.70764694 32.64401769] the nearest lat_longs are:
[[25.70764694 32.64401769]]
With distances of:
[2.43911819e-07]
-----------------------------------

Indexes of nearest lat_long [3401]
For lat_long [25.7311001 32.6327483] the nearest lat_longs are:
[[25.71387618 32.62543951]]
With distances of:
[2.0503916]
-------------------------------------
Indexes of nearest lat_long [3419]
For lat_long [25.662557 32.635053] the nearest lat_longs are:
[[25.66246368 32.63175572]]
With distances of:
[0.33063815]
-------------------------------------
Indexes of nearest lat_long [3422]
For lat_long [25.68954  32.641004] the nearest lat_longs are:
[[25.69116357 32.64074258]]
With distances of:
[0.18242279]
-------------------------------------
Indexes of nearest lat_long [3420]
For lat_long [25.69547098 32.64455281] the nearest lat_longs are:
[[25.69547097 32.64455281]]
With distances of:
[5.55974679e-07]
-------------------------------------
Indexes of nearest lat_long [3421]
For lat_long [25.30034657 32.55244786] the nearest lat_longs are:
[[25.30034657 32.55244786]]
With distances of:
[4.49705806e-07]
-------------------------------------
Indexes 

Indexes of nearest lat_long [3495]
For lat_long [31.354635 27.234694] the nearest lat_longs are:
[[31.354635 27.234694]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [1045]
For lat_long [30.841917 29.393906] the nearest lat_longs are:
[[30.841917 29.393906]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3502]
For lat_long [31.036065 28.44525 ] the nearest lat_longs are:
[[31.043063 28.497827]]
With distances of:
[5.06925235]
-------------------------------------
Indexes of nearest lat_long [3501]
For lat_long [30.824864 28.980619] the nearest lat_longs are:
[[30.829077 28.971299]]
With distances of:
[1.00569355]
-------------------------------------
Indexes of nearest lat_long [1045]
For lat_long [30.846615 29.386462] the nearest lat_longs are:
[[30.841917 29.393906]]
With distances of:
[0.88200788]
-------------------------------------
Indexes of nearest lat_long [1075]
For lat_long [30.969692 28

Indexes of nearest lat_long [3518]
For lat_long [31.25990201 32.29760118] the nearest lat_longs are:
[[31.26055437 32.30070863]]
With distances of:
[0.30414511]
-------------------------------------
Indexes of nearest lat_long [3540]
For lat_long [31.26638803 32.31435555] the nearest lat_longs are:
[[31.26638803 32.31435555]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3541]
For lat_long [31.26587558 32.30085146] the nearest lat_longs are:
[[31.26587558 32.30085146]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3558]
For lat_long [31.27038383 32.29955259] the nearest lat_longs are:
[[31.27154091 32.30097523]]
With distances of:
[0.18664159]
-------------------------------------
Indexes of nearest lat_long [3538]
For lat_long [31.25732107 32.30815767] the nearest lat_longs are:
[[31.26064753 32.30879191]]
With distances of:
[0.3747662]
-------------------------------------
Indexes of nearest lat

Indexes of nearest lat_long [3583]
For lat_long [31.27108565 32.29267515] the nearest lat_longs are:
[[31.27108565 32.29267515]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3528]
For lat_long [31.26041668 32.27910181] the nearest lat_longs are:
[[31.26041668 32.27910181]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3585]
For lat_long [31.26949223 32.29645007] the nearest lat_longs are:
[[31.26949223 32.29645007]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3586]
For lat_long [31.27015222 32.26008735] the nearest lat_longs are:
[[31.27015222 32.26008735]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3587]
For lat_long [31.27146189 32.29271272] the nearest lat_longs are:
[[31.27146189 32.29271272]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3552]
For lat_lo

Indexes of nearest lat_long [3605]
For lat_long [30.3536325  31.19910328] the nearest lat_longs are:
[[30.351873 31.201263]]
With distances of:
[0.28499684]
-------------------------------------
Indexes of nearest lat_long [3690]
For lat_long [30.35167862 31.20471531] the nearest lat_longs are:
[[30.351873 31.201263]]
With distances of:
[0.33196859]
-------------------------------------
Indexes of nearest lat_long [3706]
For lat_long [30.18825065 31.46938648] the nearest lat_longs are:
[[30.18292012 31.46567112]]
With distances of:
[0.69199269]
-------------------------------------
Indexes of nearest lat_long [3711]
For lat_long [30.31240367 31.31545781] the nearest lat_longs are:
[[30.31234045 31.31533054]]
With distances of:
[0.01409479]
-------------------------------------
Indexes of nearest lat_long [3184]
For lat_long [30.18206767 31.11101993] the nearest lat_longs are:
[[30.18210586 31.11100977]]
With distances of:
[0.00435738]
-------------------------------------
Indexes of ne

Indexes of nearest lat_long [3648]
For lat_long [30.352813 31.224481] the nearest lat_longs are:
[[30.352813 31.224481]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3699]
For lat_long [30.356687 31.201599] the nearest lat_longs are:
[[30.356687 31.201599]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3700]
For lat_long [30.389589 31.19261 ] the nearest lat_longs are:
[[30.389589 31.19261 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3626]
For lat_long [30.2426   31.477313] the nearest lat_longs are:
[[30.2426   31.477313]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3702]
For lat_long [30.250694 31.466644] the nearest lat_longs are:
[[30.250694 31.466644]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3701]
For lat_long [30.25117284 31.47901842] the nearest

Indexes of nearest lat_long [3734]
For lat_long [30.13482306 31.21791701] the nearest lat_longs are:
[[30.14007586 31.23618729]]
With distances of:
[1.8514867]
-------------------------------------
Indexes of nearest lat_long [3638]
For lat_long [30.15722  31.311313] the nearest lat_longs are:
[[30.15722  31.311313]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3745]
For lat_long [30.55079  31.257552] the nearest lat_longs are:
[[30.55079  31.257552]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3746]
For lat_long [30.476354 31.195691] the nearest lat_longs are:
[[30.476354 31.195691]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3747]
For lat_long [30.354521 31.202561] the nearest lat_longs are:
[[30.354521 31.202561]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3611]
For lat_long [30.470795 31.181623] 

Indexes of nearest lat_long [3790]
For lat_long [26.16368013 32.71424693] the nearest lat_longs are:
[[26.16307971 32.71776298]]
With distances of:
[0.35720361]
-------------------------------------
Indexes of nearest lat_long [3795]
For lat_long [26.15739779 32.7214134 ] the nearest lat_longs are:
[[26.1568561  32.72150862]]
With distances of:
[0.0609773]
-------------------------------------
Indexes of nearest lat_long [3809]
For lat_long [25.9179622  32.76003425] the nearest lat_longs are:
[[25.91540686 32.75853222]]
With distances of:
[0.32140655]
-------------------------------------
Indexes of nearest lat_long [3783]
For lat_long [26.05518454 32.16686943] the nearest lat_longs are:
[[26.06158262 32.2103766 ]]
With distances of:
[4.40384747]
-------------------------------------
Indexes of nearest lat_long [3786]
For lat_long [26.16307971 32.71776298] the nearest lat_longs are:
[[26.16368013 32.71424693]]
With distances of:
[0.35720361]
-------------------------------------
Indexe

Indexes of nearest lat_long [3829]
For lat_long [27.252037 33.815172] the nearest lat_longs are:
[[27.252037 33.815172]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3957]
For lat_long [27.25166047 33.81470844] the nearest lat_longs are:
[[27.252037 33.815172]]
With distances of:
[0.06207118]
-------------------------------------
Indexes of nearest lat_long [3914]
For lat_long [27.16474678 33.8213102 ] the nearest lat_longs are:
[[27.16653819 33.82279261]]
With distances of:
[0.24735793]
-------------------------------------
Indexes of nearest lat_long [3850]
For lat_long [27.22946848 33.83646631] the nearest lat_longs are:
[[27.22813603 33.83866101]]
With distances of:
[0.26275322]
-------------------------------------
Indexes of nearest lat_long [3909]
For lat_long [27.19502003 33.82678863] the nearest lat_longs are:
[[27.184204 33.826214]]
With distances of:
[1.20402929]
-------------------------------------
Indexes of nearest lat_long [

Indexes of nearest lat_long [3934]
For lat_long [27.179245 33.807262] the nearest lat_longs are:
[[27.179245 33.807262]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3887]
For lat_long [25.555393 34.592654] the nearest lat_longs are:
[[25.555393 34.592654]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3958]
For lat_long [27.247659 33.82487 ] the nearest lat_longs are:
[[27.247659 33.82487 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3909]
For lat_long [27.184204 33.826214] the nearest lat_longs are:
[[27.184204 33.826214]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3910]
For lat_long [27.219095 33.838156] the nearest lat_longs are:
[[27.21909534 33.83815563]]
With distances of:
[5.2610503e-05]
-------------------------------------
Indexes of nearest lat_long [3891]
For lat_long [25.069389 34.884499] 

Indexes of nearest lat_long [3943]
For lat_long [27.081987 33.858367] the nearest lat_longs are:
[[27.081987 33.858367]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3856]
For lat_long [26.976562 33.913739] the nearest lat_longs are:
[[26.976562 33.913739]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3945]
For lat_long [27.082084 33.861252] the nearest lat_longs are:
[[27.082084 33.861252]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3857]
For lat_long [27.213706 33.842024] the nearest lat_longs are:
[[27.213706 33.842024]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3947]
For lat_long [27.252172 33.818728] the nearest lat_longs are:
[[27.252172 33.818728]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [3948]
For lat_long [27.289575 33.761395] the nearest lat

Indexes of nearest lat_long [3986]
For lat_long [26.564008 31.708463] the nearest lat_longs are:
[[26.565403 31.708621]]
With distances of:
[0.15591084]
-------------------------------------
Indexes of nearest lat_long [3986]
For lat_long [26.565603 31.708675] the nearest lat_longs are:
[[26.565403 31.708621]]
With distances of:
[0.02287828]
-------------------------------------
Indexes of nearest lat_long [3990]
For lat_long [26.669179 31.502025] the nearest lat_longs are:
[[26.66913  31.501907]]
With distances of:
[0.01292922]
-------------------------------------
Indexes of nearest lat_long [3989]
For lat_long [26.66913  31.501907] the nearest lat_longs are:
[[26.669179 31.502025]]
With distances of:
[0.01292922]
-------------------------------------
Indexes of nearest lat_long [4045]
For lat_long [26.560028 31.707108] the nearest lat_longs are:
[[26.56002781 31.70710805]]
With distances of:
[2.17044335e-05]
-------------------------------------
Indexes of nearest lat_long [4086]
Fo

Indexes of nearest lat_long [4041]
For lat_long [26.538593 31.707213] the nearest lat_longs are:
[[26.542948 31.712804]]
With distances of:
[0.73744995]
-------------------------------------
Indexes of nearest lat_long [4086]
For lat_long [26.342289 31.884305] the nearest lat_longs are:
[[26.34538508 31.88455501]]
With distances of:
[0.34516861]
-------------------------------------
Indexes of nearest lat_long [4035]
For lat_long [26.549785 31.694077] the nearest lat_longs are:
[[26.551319 31.698295]]
With distances of:
[0.45290577]
-------------------------------------
Indexes of nearest lat_long [4015]
For lat_long [26.551319 31.698295] the nearest lat_longs are:
[[26.551403 31.698936]]
With distances of:
[0.06443929]
-------------------------------------
Indexes of nearest lat_long [3975]
For lat_long [26.700333 31.606733] the nearest lat_longs are:
[[26.69677484 31.60331427]]
With distances of:
[0.52141832]
-------------------------------------
Indexes of nearest lat_long [4003]
Fo

Indexes of nearest lat_long [4111]
For lat_long [26.83108569 31.37643144] the nearest lat_longs are:
[[26.83792221 31.42394379]]
With distances of:
[4.77511182]
-------------------------------------
Indexes of nearest lat_long [4067]
For lat_long [26.62442673 31.53183433] the nearest lat_longs are:
[[26.62401771 31.5316638 ]]
With distances of:
[0.04853728]
-------------------------------------
Indexes of nearest lat_long [4034]
For lat_long [26.5384048  31.67188178] the nearest lat_longs are:
[[26.549785 31.694077]]
With distances of:
[2.54477379]
-------------------------------------
Indexes of nearest lat_long [3993]
For lat_long [26.9080338 31.4338309] the nearest lat_longs are:
[[26.90679215 31.43104171]]
With distances of:
[0.30911423]
-------------------------------------
Indexes of nearest lat_long [4036]
For lat_long [26.74542573 31.61892827] the nearest lat_longs are:
[[26.700333 31.606733]]
With distances of:
[5.15830084]
-------------------------------------
Indexes of near

Indexes of nearest lat_long [4182]
For lat_long [27.90947216 34.32567521] the nearest lat_longs are:
[[27.906941 34.326242]]
With distances of:
[0.28690962]
-------------------------------------
Indexes of nearest lat_long [4122]
For lat_long [27.875407 34.318455] the nearest lat_longs are:
[[27.873564 34.317922]]
With distances of:
[0.211523]
-------------------------------------
Indexes of nearest lat_long [4121]
For lat_long [27.873564 34.317922] the nearest lat_longs are:
[[27.875407 34.318455]]
With distances of:
[0.211523]
-------------------------------------
Indexes of nearest lat_long [4168]
For lat_long [29.5902404 32.7222317] the nearest lat_longs are:
[[29.593128 32.716771]]
With distances of:
[0.61796764]
-------------------------------------
Indexes of nearest lat_long [4124]
For lat_long [27.939353 34.38367 ] the nearest lat_longs are:
[[27.939353 34.38367 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4171]
For lat_long [28

Indexes of nearest lat_long [4176]
For lat_long [29.39205  34.793026] the nearest lat_longs are:
[[29.388392 34.807918]]
With distances of:
[1.49903392]
-------------------------------------
Indexes of nearest lat_long [4144]
For lat_long [29.491433 34.894008] the nearest lat_longs are:
[[29.492467 34.898851]]
With distances of:
[0.48263368]
-------------------------------------
Indexes of nearest lat_long [4185]
For lat_long [29.491281 34.900613] the nearest lat_longs are:
[[29.490479 34.899327]]
With distances of:
[0.15311875]
-------------------------------------
Indexes of nearest lat_long [4192]
For lat_long [27.854711 34.303488] the nearest lat_longs are:
[[27.854711 34.303488]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4170]
For lat_long [28.98013313 34.65789021] the nearest lat_longs are:
[[29.033822 34.662779]]
With distances of:
[5.98883027]
-------------------------------------
Indexes of nearest lat_long [4120]
For lat_long [

Indexes of nearest lat_long [4220]
For lat_long [27.91601  34.330108] the nearest lat_longs are:
[[27.91601  34.330108]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4139]
For lat_long [28.012092 34.42887 ] the nearest lat_longs are:
[[28.012092 34.42887 ]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4222]
For lat_long [27.859667 34.316425] the nearest lat_longs are:
[[27.859667 34.316425]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4180]
For lat_long [27.856145 34.301682] the nearest lat_longs are:
[[27.854711 34.303488]]
With distances of:
[0.23864015]
-------------------------------------
Indexes of nearest lat_long [4224]
For lat_long [27.8825   34.298582] the nearest lat_longs are:
[[27.8825   34.298582]]
With distances of:
[0.]
-------------------------------------
Indexes of nearest lat_long [4225]
For lat_long [27.921795 34.322666] the nea