In [17]:
# import geopandas as gpd
# import geopy
# from shapely.geometry import Point
# from geopy.geocoders import Nominatim

import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 10000)
pd.set_option('display.width', 10000)


In [21]:
df = pd.read_excel('Atm_bank_misr.xlsx')
#df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4275 entries, 0 to 4274
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   governorate  4275 non-null   object 
 1   Region       4275 non-null   object 
 2   Lat          4275 non-null   float64
 3   Long         4275 non-null   float64
dtypes: float64(2), object(2)
memory usage: 133.7+ KB


In [33]:

lat_longs =df[['Lat','Long']]#
lat_longs2 = lat_longs.drop_duplicates()

lat_longs = np.array(lat_longs2)
print(lat_longs.shape)
r={}
result = pd.DataFrame(r)
id=[]
for i in range(len(df['Lat'])):
    id.append(i+1)
result.insert(loc=0 , column="ATM ID" ,value=id )
result.insert(loc=1 , column="Governorate" ,value=df['governorate'] )
result.insert(loc=2 , column="Region" ,value=df['Region'] )
result.insert(loc=3 , column="Latitude" ,value=df['Lat'] )
result.insert(loc=4 , column="Longitude" ,value=df['Long'] )
result.head()
#result.to_excel("BM_ATM.xlsx")

(3328, 2)


ATM ID Governorate     Region   Latitude  Longitude
0       1   Al Fayyum  Al-Fayyum  29.304412  30.853546
1       2   Al Fayyum  Al-Fayyum  29.319696  30.835641
2       3   Al Fayyum  Al-Fayyum  29.308199  30.842229
3       4   Al Fayyum   Sinnuris  29.408575  30.865073
4       5   Al Fayyum       Itsa  29.236966  30.790194

```python
def get_distance (lat1, lon1, lat2, lon2) :
    p = 0.017453292519943295    # Math.PI / 180
    c = Math.cos
    a = 0.5 - c((lat2 - lat1) * p)/2 + 
          c(lat1 * p) * c(lat2 * p) * 
          (1 - c((lon2 - lon1) * p))/2;

    return 12742 * Math.asin(Math.sqrt(a)); // 2 * R; R = 6371 km
```

In [36]:
k = 1

for i in range(len(lat_longs)):
    
    dist_list = []
    for j in range(len(lat_longs)): 
        if i != j : 
            dist_list.append(np.sqrt(np.square(lat_longs[i][0] - lat_longs[j][0])+np.square(lat_longs[i][1]-lat_longs[j][1])))
    
    least_k = np.argsort(np.array(dist_list))[:k]
    print('indexes of nearest lat_long',least_k)
    print('For lat_long',lat_longs[i],'the nearest lat_longs are:')
    print(lat_longs[least_k])

    
    
    

indexes of nearest lat_long [20]
For lat_long [29.30441208 30.85354563] the nearest lat_longs are:
[[29.39694049 30.82468411]]
indexes of nearest lat_long [7]
For lat_long [29.319696 30.835641] the nearest lat_longs are:
[[29.321487 30.837896]]
indexes of nearest lat_long [9]
For lat_long [29.308199 30.842229] the nearest lat_longs are:
[[29.308889 30.847499]]
indexes of nearest lat_long [15]
For lat_long [29.40857519 30.86507307] the nearest lat_longs are:
[[29.47427641 30.9549612 ]]
indexes of nearest lat_long [27]
For lat_long [29.23696578 30.79019445] the nearest lat_longs are:
[[29.24143653 30.79518521]]
indexes of nearest lat_long [8]
For lat_long [29.30772267 30.84613982] the nearest lat_longs are:
[[29.322145 30.837087]]
indexes of nearest lat_long [13]
For lat_long [29.31542035 30.85217852] the nearest lat_longs are:
[[29.36074053 30.68325785]]
indexes of nearest lat_long [7]
For lat_long [29.321487 30.837896] the nearest lat_longs are:
[[29.321487 30.837896]]
indexes of neare

KeyboardInterrupt: 